steps:
- name: golang
  args:
  - go
  - build
  - -o
  - server
  - '.'
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - gcr.io/$PROJECT_ID/demo-file-server:$COMMIT_SHA
  - '.'
- name: gcr.io/cloud-builders/docker
  args:
  - push
  - gcr.io/$PROJECT_ID/demo-file-server:$COMMIT_SHA
images:
- gcr.io/$PROJECT_ID/demo-file-server:$COMMIT_SHA
